
- name: Abhängigkeiten installieren
  apt:
    pkg: "{{ item }}"
    state: installed
  with_items:
    - build-essential
    - checkinstall
    - pkg-config
    - libnl-3-dev
    - libnl-genl-3-dev

- name: batctl-Quellen laden und entpacken
  unarchive: src=batctl-2016.4.tar.gz dest=/usr/src

- stat: path=/usr/local/sbin/batctl
  register: batctl

- name: batctl Version prüfen
  shell: '{{batctl.stat.path}} -v | grep -oE "batctl [0-9]+\.[0-9]+"'
  when: batctl.stat.exists == True
  changed_when: False
  register: batctl_version

- name: batctl bauen
  shell: "make && checkinstall -y make install"
  args:
    chdir: /usr/src/batctl-2016.4
  when: batctl.stat.exists == False or batctl_version.stdout_lines[0] != "batctl 2016.4"

# creating batman interface
- name: Create interfaces - batman file
  template: src="batman.j2" dest="/etc/network/interfaces.d/10_batman.cfg"
  notify:
    - restart networking

#append line in interfaces file for reading additional config files
- name: let read interfaces from interfaces
  lineinfile: dest="/etc/network/interfaces" line="source /etc/network/interfaces.d/*"
  notify:
    - restart networking

- name: Routingtabelle 42 auch ffnet nennen
  lineinfile: dest="/etc/iproute2/rt_tables" line="42   ffnet"

- name: Drei Sekunden nach Kernelpanik automatisch neu starten
  sysctl: name="kernel.panic" value=3 sysctl_set=yes state=present reload=yes
